# Generated by Django 4.2 on 2023-04-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('head_img', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('id_code', models.IntegerField()),
            ],
        ),
    ]
