# Generated by Django 4.2 on 2023-04-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id_code',
            field=models.IntegerField(default=0),
        ),
    ]
