# Generated by Django 4.2 on 2023-04-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_user_info_phone_alter_user_info_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
