# Generated by Django 4.2 on 2023-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_user_info_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
