# Generated by Django 4.2 on 2023-04-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_user_info_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='head_img',
            field=models.TextField(default=''),
        ),
    ]
