# Generated by Django 4.2 on 2023-05-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='txt',
        ),
    ]
