# Generated by Django 4.2 on 2023-05-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_rename_article_article_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('value', models.TextField(default='')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
