# Generated by Django 4.2 on 2023-05-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chart',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
